# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Hello DockerCon
        run: echo Hello, world!

      - name: Get 25% off WSL Tips, Tricks and Techniques
        run: echo Hello, world!

      - name: With discount code 25WSL2
        run: echo Hello, world!

      - name: When buying the ebook direct from Packt
        run: echo Hello, world!

      - name: See https://wsl.tips/book
        run: echo Hello, world!
